 <?php
function queenattack_menu (){
        $items = array();
        $items['queenattack'] = array(
            'title' => 'Let play queenattack',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('queenattack_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['result'] = array(
            'title' => 'Result Page',
            'page callback' => 'result_function',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
}

function queenattack_form() {
    $form['first_position'] = array(
        '#title' => 'Queen Position',
        '#type' => 'textfield',
        '#description' => t('Please enter your queen position'),


    );
    $form['second_position'] = array(
        '#title' => 'Second Position',
        '#type' => 'textfield',
        '#description' => t('Please enter your second position'),

    );
    $form['submit'] = array(
        '#type' => "submit",
        '#value' => 'Go!',

    );
    return $form;
}

function queenattack_form_submit($form, &$form_state) {
    $first_number = $form_state['values']['first_position'];
    $first_number_exploded = explode(' ', $first_number);
    $empty_array = array();
    foreach($first_number_exploded as $element) {
        array.push($empty_array, $element);
    }
    $_SESSION['array1'] = $empty_array;
    $form_state['redirect'] = 'result';
}

function result_function() {
    $empty_string = $_SESSION['array1'];
    return $empty_string;
}
